workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Credencial.xcworkspace"
        XCODE_SCHEME: "Credencial"
      xcode: latest
    scripts:
  - name: Install dependencies
    script: |
      npm install

  - name: Set iOS platform to 13.0
    script: |
      sed -i '' 's/platform :ios, .*/platform :ios, '\''13.0'\''/' ios/Podfile

  - name: Clean and install CocoaPods
    script: |
      cd ios
      rm -rf Pods Podfile.lock
      pod install
      pod update hermes-engine --no-repo-update
      cd ..

  - name: Build .ipa for release
    script: |
      xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos -derivedDataPath build

    artifacts:
      - build/Build/Products/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - aleweb3.0@gmail.com