workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/Credencial.xcworkspace"
        XCODE_SCHEME: "Credencial"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Clean and update CocoaPods
        script: |
              cd ios
              rm -rf Pods Podfile.lock
              echo "👉 Running pod install"
              pod install || { echo "❌ pod install failed"; exit 1; }
              echo "✅ pod install OK"
              echo "👉 Updating Hermes"
              pod update hermes-engine --no-repo-update || { echo "❌ pod update failed"; exit 1; }
              cd ..
      - name: Debug iOS folder
        script: |
              echo "📂 Contenido de ios/"
              ls -la ios/
              echo "📂 Contenido de ios/Credencial.xcworkspace/"
              ls -la ios/Credencial.xcworkspace || echo "❌ No existe la carpeta xcworkspace"
      - name:  Verify xcworkspace exists
        script: |
          if [ ! -f ios/Credencial.xcworkspace/contents.xcworkspacedata ]; then
            echo "❌ .xcworkspace not generated!"
            exit 1
          fi
          
      - name: Build .ipa for release
        script: |
          xcodebuild -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -configuration Release -sdk iphoneos -derivedDataPath build
    artifacts:
      - build/Build/Products/Release-iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - aleweb3.0@gmail.com
